from pathlib import Path
import re, base64, json, subprocess, sys
root=Path(__file__).resolve().parent
sales=(root/'SALESRETURN_v208_DECODED.html').read_text()
damage=(root/'DAMAGEDSTOCK_v208_DECODED.html').read_text()
dist=(root/'dist/index.html').read_text()
checks=[]
def ck(n,v): checks.append((n,bool(v)))
ck('package version',json.loads((root/'package.json').read_text())['version']=='2.0.8')
ck('tauri version',json.loads((root/'src-tauri/tauri.conf.json').read_text())['version']=='2.0.8')
ck('cargo version','version = "2.0.8"' in (root/'src-tauri/Cargo.toml').read_text())
ck('Sales Return condition select','class="li-condition"' in sales)
ck('Sales Return damaged option','value="damaged">Damaged' in sales)
ck('Damage reason required','Enter a damage reason for every damaged return item.' in sales)
ck('Saleable stock filter','function srSaleableItems' in sales)
ck('Damage references','function srDamageReference' in sales and 'DSR-' in sales)
ck('Damage record sync','function srSyncDamageRows' in sales)
ck('Damage table insert',"from('damaged_stock').insert(rows)" in sales)
ck('Sales Return PDF condition','Condition / Damage Ref' in sales)
ck('Sales Return clickable damage ref','damage-ref-link' in sales)
ck('Damage location selector','id="d_location"' in damage)
ck('Damage Main Warehouse adjustment','decrement_stock' in damage and 'increment_stock' in damage)
ck('Damage Vehicle inventory link','nag_location_inventory_v1' in damage)
ck('Damage Mini Store inventory link','nag_mini_store_inventory_v1' in damage)
ck('Vehicle damage merge','nag_stock_transfers_v1' in damage and "vehicle_damage" in damage)
ck('Mini Store damage merge','nag_mini_store_transfers_v1' in damage and "mini_damage" in damage)
ck('Sales Return damage merge',"source_type==='sales_return'" in damage)
ck('Damage report reference','<th>Reference</th>' in damage)
ck('Damage report location','<th>Location</th>' in damage)
ck('Damage report source','<th>Source</th>' in damage)
ck('Linked rows read-only',"source_type!=='sales_return'" in damage and 'it.read_only' in damage)
ck('SQL migration exists',(root/'SUPABASE_SALES_RETURN_DAMAGE_LINK_v208.sql').exists())
ck('SQL source columns','source_reference' in (root/'SUPABASE_SALES_RETURN_DAMAGE_LINK_v208.sql').read_text())
ck('Shell opens Sales Return',"nag-open-sales-return" in dist)
ck('Shell opens Damaged Stock',"nag-open-damaged-stock" in dist)
for var,src in [('SALESRETURN',sales),('DAMAGEDSTOCK',damage)]:
 m=re.search(var+r'=b64utf8\("(.*?)"\)',dist,re.S);ck(var+' embedded',m is not None);ck(var+' embedded matches',bool(m) and base64.b64decode(m.group(1)).decode()==src)
for label,src in [('Sales Return',sales),('Damaged Stock',damage),('Desktop shell',dist)]:
 scripts=re.findall(r'<script(?:\s[^>]*)?>([\s\S]*?)</script>',src,re.I);tmp=root/('.v208_'+label.lower().replace(' ','_')+'.js');tmp.write_text('\n'.join(scripts));r=subprocess.run(['node','--check',str(tmp)],capture_output=True,text=True);tmp.unlink(missing_ok=True);ck(label+' JavaScript syntax',r.returncode==0)
failed=[n for n,v in checks if not v]
for n,v in checks: print(('PASS ' if v else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed: sys.exit(1)
