from pathlib import Path
import re,base64,json,subprocess,sys
root=Path(__file__).resolve().parent
shell=(root/'dist'/'index.html').read_text()
inv=(root/'INVENTORY_v202_DECODED.html').read_text()
mini=(root/'MINI_STORE_v201_DECODED.html').read_text()
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('package version',json.loads((root/'package.json').read_text())['version']=='2.0.2')
ck('tauri version',json.loads((root/'src-tauri'/'tauri.conf.json').read_text())['version']=='2.0.2')
ck('cargo version','version = "2.0.2"' in (root/'src-tauri'/'Cargo.toml').read_text())
ck('main.rs present',(root/'src-tauri'/'src'/'main.rs').exists())
ck('warehouse card','id="pickWarehouseInventory"' in shell)
ck('warehouse permission label',"['pickWarehouseInventory','Main Warehouse Inventory']" in shell)
ck('warehouse in visibility list',"'pickInventory','pickWarehouseInventory','pickVehicleStock'" in shell)
ck('warehouse click handler',"document.getElementById('pickWarehouseInventory').onclick=openWarehouseInventory" in shell)
ck('warehouse permission guard',"nagCanOpenModule('pickWarehouseInventory')" in shell)
ck('warehouse readonly mode',"'warehouse-readonly'" in shell)
ck('admin duplicate hidden',"id==='pickWarehouseInventory'?'none':''" in shell)
ck('Mini Store permission inventory label',"['pickMiniStore','Mini Store Inventory']" in shell)
ck('cashier Mini Store opens inventory mode',"if(s&&s.role!=='admin')openMiniStoreMode('inventory','My Mini Store Inventory')" in shell)
ck('admin Mini Store opens full mode',"else openMiniStoreMode('full','Mini Store')" in shell)
ck('cashier Mini Store card inventory text','Only products currently available in my assigned Mini Store' in shell)
ck('Mini Store inventory mode hides settlement',"if(mode==='inventory'){showCard('miniStoreSettlementCard',false)" in mini)
ck('Mini Store inventory mode hides return',"showCard('miniStoreReturnCard',false)" in mini)
ck('Mini Store inventory mode hides report',"showCard('miniStoreReportCard',false)" in mini)
ck('Mini Store inventory mode hides bill',"showCard('miniStoreBillCard',false)" in mini)
ck('Mini Store inventory mode hides history',"showCard('miniStoreHistoryCard',false)" in mini)
ck('Mini Store assigned filter','allowedMiniStores' in mini and 'miniStoreAllowed' in mini)
ck('Mini Store positive stock filter','n(rows[c])>0' in mini)
ck('Inventory mode helper','function inventoryMode()' in inv)
ck('Inventory admin helper','function canManageProducts()' in inv)
ck('Inventory readonly UI','Main Warehouse Inventory — مخزون المستودع الرئيسي' in inv)
ck('Add hidden for cashier',"$('btnAdd').style.display='none'" in inv)
ck('Import hidden for cashier',"$('btnImportExcel').style.display='none'" in inv)
ck('Edit cell conditional',"canManageProducts()?'<td><button class=\"icon-btn\"" in inv)
ck('Open add protected',"function openAdd(){\n    if(!canManageProducts())" in inv)
ck('Open edit protected',"function openEdit(id){\n    if(!canManageProducts())" in inv)
ck('Save protected',"function saveProduct(){\n    if(!canManageProducts())" in inv)
ck('Delete protected',"function deleteProduct(){\n    if(!canManageProducts())" in inv)
ck('Import protected',"Main Warehouse inventory is read-only for cashiers" in inv)
ck('PDF retained',"id=\"btnPdf\"" in inv)
ck('Print retained',"id=\"btnPrint\"" in inv)
ck('Export retained',"id=\"btnExportExcel\"" in inv)
ck('price permissions retained','function canViewCost()' in inv and 'function myPriceAccess()' in inv)
m=re.search(r'INVENTORY=b64utf8\("([A-Za-z0-9+/=]+)"\)',shell)
ck('embedded Inventory found',m is not None)
ck('embedded Inventory matches source',bool(m) and base64.b64decode(m.group(1)).decode()==inv)
# syntax checks
for label,source in [('Inventory',inv),('Mini Store',mini),('Desktop shell',shell)]:
 scripts=re.findall(r'<script(?:\s[^>]*)?>(.*?)</script>',source,re.S)
 temp=root/('.validate_'+label.lower().replace(' ','_')+'.js')
 temp.write_text('\n'.join(scripts))
 try:
  r=subprocess.run(['node','--check',str(temp)],capture_output=True,text=True)
  ck(label+' JavaScript syntax',r.returncode==0)
 finally: temp.unlink(missing_ok=True)
failed=[n for n,c in checks if not c]
for n,c in checks: print(('PASS ' if c else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed:
 print('\n'.join('FAILED: '+x for x in failed));sys.exit(1)
