from pathlib import Path
import base64,json,re,subprocess,sys
root=Path(__file__).resolve().parent
module=(root/'STOCK_CONTROL_v199_DECODED.html').read_text(encoding='utf-8')
dist=(root/'dist'/'index.html').read_text(encoding='utf-8')
checks=[]
def check(name,ok): checks.append((name,bool(ok)))
check('package version',json.loads((root/'package.json').read_text())['version']=='1.9.9')
check('tauri version',json.loads((root/'src-tauri'/'tauri.conf.json').read_text())['version']=='1.9.9')
check('cargo version','version = "1.9.9"' in (root/'src-tauri'/'Cargo.toml').read_text())
check('main rs exists',(root/'src-tauri'/'src'/'main.rs').exists())
check('central report title','Central Stock Control Report' in module)
check('company PDF header','function companyHeader()' in module)
check('company PDF footer','function companyFooter()' in module)
check('company logo','function companyLogo()' in module)
check('company VAT','311157282200003' in module)
check('company CR','3451102031' in module)
check('company telephone','0537859509' in module)
check('company national address','7027457311' in module)
check('A4 page','@page{size:A4' in module)
check('preview report button','id="previewReport"' in module)
check('print save button','id="printDocument"' in module)
check('report PDF function','function reportHtml()' in module)
check('reference button','class="refbtn" data-key=' in module)
check('reference opener','function openReference(key)' in module)
check('sale invoice PDF','function invoiceHtml(d)' in module)
check('movement PDF','function movementHtml(d)' in module)
check('ZATCA QR','function zatcaData(d)' in module)
check('vehicle movement records',"nag_stock_transfers_v1" in module)
check('vehicle sale records',"nag_vehicle_sales_v1" in module)
check('mini movement records',"nag_mini_store_transfers_v1" in module)
check('mini sale records',"nag_mini_store_sales_v1" in module)
check('return references','return' in module)
check('damage references','damage' in module)
check('missing references','missing' in module)
check('correction references','correction' in module)
check('cancellation references','cancellation' in module)
check('correction request references','correction_request' in module)
check('Cash totals','Cash Sales' in module)
check('Credit totals','Credit Sales' in module)
check('Paid totals','Paid Amount' in module)
check('Pending totals','Pending Amount' in module)
check('print headings repeat','.doc-table thead{display:table-header-group}' in module)
check('rows avoid split','page-break-inside:avoid' in module)
release=(root/'.github'/'workflows'/'release-desktop.yml').read_text()
check('release workflow default v1.9.9',"default: 'v1.9.9'" in release)
vehicle=(root/'VEHICLE_STOCK_v187_DECODED.html').read_text(encoding='utf-8')
mini=(root/'MINI_STORE_v197_DECODED.html').read_text(encoding='utf-8')
vm=re.search(r'var VEHICLE_STOCK=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
mm=re.search(r'var MINI_STORE=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
check('embedded Vehicle Stock unchanged',bool(vm) and base64.b64decode(vm.group(1)).decode('utf-8')==vehicle)
check('embedded Mini Store unchanged',bool(mm) and base64.b64decode(mm.group(1)).decode('utf-8')==mini)
m=re.search(r'var STOCK_CONTROL=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
check('embedded stock control found',m is not None)
check('embedded stock control matches',bool(m) and base64.b64decode(m.group(1)).decode('utf-8')==module)
scripts=re.findall(r'<script>(.*?)</script>',module,flags=re.S)
tmp=root/'.validate_stock_control_v199.js';tmp.write_text('\n'.join(scripts),encoding='utf-8')
try:
 r=subprocess.run(['node','--check',str(tmp)],capture_output=True,text=True)
 check('Stock Control JavaScript syntax',r.returncode==0)
 if r.returncode: print(r.stderr)
finally: tmp.unlink(missing_ok=True)
# Shell syntax
scripts=re.findall(r'<script>(.*?)</script>',dist,flags=re.S)
tmp=root/'.validate_shell_v199.js';tmp.write_text('\n'.join(scripts),encoding='utf-8')
try:
 r=subprocess.run(['node','--check',str(tmp)],capture_output=True,text=True)
 check('Desktop shell JavaScript syntax',r.returncode==0)
 if r.returncode: print(r.stderr)
finally: tmp.unlink(missing_ok=True)
failed=[n for n,o in checks if not o]
for n,o in checks: print(('PASS ' if o else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed: sys.exit(1)
