from pathlib import Path
import json,re,base64,subprocess,sys
root=Path(__file__).resolve().parent
dist=(root/'dist/index.html').read_text()
vehicle=(root/'VEHICLE_STOCK_v201_DECODED.html').read_text()
mini=(root/'MINI_STORE_v201_DECODED.html').read_text()
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck('package version',json.loads((root/'package.json').read_text())['version']=='2.0.1')
ck('tauri version',json.loads((root/'src-tauri/tauri.conf.json').read_text())['version']=='2.0.1')
ck('cargo version','version = "2.0.1"' in (root/'src-tauri/Cargo.toml').read_text())
ck('main.rs exists',(root/'src-tauri/src/main.rs').exists())
ck('admin-only module list','pickStockControl' in dist and 'ADMIN_ONLY_MODULES' in dist)
for x in ['pickDashboard','pickStockControl','pickEmployees','pickKhurooj','pickSalary','pickAdvance','pickCommercialInvoice','pickSettings','pickCashierPanel','pickCashierReport','pickDiscountRequests']:
 ck('admin only '+x, re.search(r'var ADMIN_ONLY_MODULES=\[[^\]]*'+re.escape("'"+x+"'")+r'[^\]]*\]',dist) is not None)
mods=re.search(r'var MODS=\[(.*?)\];\n    var ADMIN_ONLY_MODULES',dist,re.S)
ck('cashier module list found',mods is not None)
mods_text=mods.group(1) if mods else ''
ck('stock control excluded from permissions','pickStockControl' not in mods_text)
ck('employees excluded from permissions','pickEmployees' not in mods_text)
ck('exact empty permissions supported','Array.isArray(user.perms)' in dist)
ck('new cashier starts empty',"perms:[],priceAccess:'retail'" in dist)
ck('no minimum module requirement','Select at least one module.' not in dist)
ck('home capture guard',"homeGuard.addEventListener('click'" in dist and 'stopImmediatePropagation' in dist)
ck('global permission guard','window.nagCanOpenModule' in dist)
ck('inventory opener permission guard',"nagCanOpenModule('pickInventory')" in dist)
ck('vehicle positive stock only',"Object.keys(rows).filter(function(c){return n(rows[c])>0})" in vehicle)
ck('mini positive stock only',"Object.keys(rows).filter(function(c){return n(rows[c])>0})" in mini)
ck('vehicle assigned location guard','function vehicleAllowed' in vehicle)
ck('mini assigned location guard','function miniStoreAllowed' in mini)
ck('vehicle cashier location filtering','function allowedVehicles' in vehicle)
ck('mini cashier location filtering','function allowedMiniStores' in mini)
ck('dynamic vehicle inventory label','Only products currently available in my assigned vehicle' in dist)
ck('dynamic mini inventory label','Only products currently available in my assigned Mini Store' in dist)
vm=re.search(r'var VEHICLE_STOCK=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
mm=re.search(r'var MINI_STORE=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
ck('embedded vehicle found',vm is not None)
ck('embedded mini found',mm is not None)
ck('embedded vehicle matches',bool(vm) and base64.b64decode(vm.group(1)).decode()==vehicle)
ck('embedded mini matches',bool(mm) and base64.b64decode(mm.group(1)).decode()==mini)
for label,src in [('shell',dist),('vehicle',vehicle),('mini',mini)]:
 scripts=re.findall(r'<script>(.*?)</script>',src,re.S)
 t=root/f'.v201_{label}.js';t.write_text('\n'.join(scripts))
 r=subprocess.run(['node','--check',str(t)],capture_output=True,text=True);t.unlink(missing_ok=True)
 ck(label+' JavaScript syntax',r.returncode==0)
failed=[n for n,c in checks if not c]
for n,c in checks: print(('PASS ' if c else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed: sys.exit(1)
