from pathlib import Path
import re,json,base64,subprocess,sys
root=Path(__file__).resolve().parent
dist=(root/'dist/index.html').read_text()
veh=(root/'VEHICLE_STOCK_v203_DECODED.html').read_text()
mini=(root/'MINI_STORE_v203_DECODED.html').read_text()
assigned=(root/'ASSIGNED_INVENTORY_v203_DECODED.html').read_text()
checks=[]
def c(n,v):checks.append((n,bool(v)))
c('package version',json.loads((root/'package.json').read_text())['version']=='2.0.3')
c('tauri version',json.loads((root/'src-tauri/tauri.conf.json').read_text())['version']=='2.0.3')
c('cargo version','version = "2.0.3"' in (root/'src-tauri/Cargo.toml').read_text())
c('assigned inventory embedded','var ASSIGNED_INVENTORY=b64utf8(' in dist)
c('dedicated builder','function buildAssignedInventoryDoc' in dist)
c('inventory route uses dedicated module',"openTool(buildAssignedInventoryDoc(kind,s)" in dist)
c('vehicle full module admin only',"'pickVehicleStock'" in re.search(r'var ADMIN_ONLY_MODULES=\[[^;]+',dist).group(0))
c('mini full module admin only',"'pickMiniStore'" in re.search(r'var ADMIN_ONLY_MODULES=\[[^;]+',dist).group(0))
c('vehicle removed from cashier permissions',"['pickVehicleStock','Vehicle Stock']" not in dist)
c('mini removed from cashier permissions',"['pickMiniStore','Mini Store Inventory']" not in dist)
c('cashier css hides Khurooj','body.nag-cashier-session #pickKhurooj' in dist)
c('cashier css hides full vehicle','body.nag-cashier-session #pickVehicleStock' in dist)
c('cashier css hides full mini','body.nag-cashier-session #pickMiniStore' in dist)
c('strong hidden class','.nag-force-hidden{display:none!important}' in dist)
c('old perms sanitized','return p.filter(function(id){return ADMIN_ONLY_MODULES.indexOf(id)===-1})' in dist)
c('assignment normalization','function nagNormUser' in dist and 'assignedRows' in dist)
c('mini title','My Mini Store Inventory' in assigned)
c('vehicle title','My Vehicle Inventory' in assigned)
c('positive stock filter','n(stock[code])>0' in assigned)
c('read only no save buttons','Save Mini Store' not in assigned and 'Record Damage' not in assigned and 'Return to Main Warehouse' not in assigned)
c('cashier scope wins vehicle',"window.NAG_CASHIER_SCOPE&&window.NAG_CASHIER_SCOPE.role==='cashier'" in veh)
c('cashier scope wins mini',"window.NAG_CASHIER_SCOPE&&window.NAG_CASHIER_SCOPE.role==='cashier'" in mini)
c('vehicle mode forced inventory',"return 'inventory'" in veh[veh.find('function moduleMode'):veh.find('function allowedVehicles')])
c('mini mode forced inventory',"return 'inventory'" in mini[mini.find('function moduleMode'):mini.find('function showCard')])
c('warehouse permission retained',"['pickWarehouseInventory','Main Warehouse Inventory']" in dist)
for var,src in [('VEHICLE_STOCK',veh),('MINI_STORE',mini),('ASSIGNED_INVENTORY',assigned)]:
 m=re.search(rf'var {var}=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist);c(var+' embedded found',m is not None);c(var+' embedded matches',bool(m) and base64.b64decode(m.group(1)).decode()==src)
for label,src in [('Vehicle',veh),('Mini',mini),('Assigned',assigned),('Shell',dist)]:
 scripts=re.findall(r'<script>(.*?)</script>',src,re.S);tmp=root/f'.check_{label}.js';tmp.write_text('\n'.join(scripts));r=subprocess.run(['node','--check',str(tmp)],capture_output=True,text=True);tmp.unlink(missing_ok=True);c(label+' JavaScript syntax',r.returncode==0)
failed=[n for n,v in checks if not v]
for n,v in checks:print(('PASS ' if v else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed:sys.exit(1)
