from pathlib import Path
import re, base64, json, subprocess, sys
root=Path(__file__).resolve().parent
dist=(root/'dist'/'index.html').read_text(encoding='utf-8')
sales=(root/'SALESRETURN_v205_DECODED.html').read_text(encoding='utf-8')
inv=(root/'INVENTORY_v205_DECODED.html').read_text(encoding='utf-8')
checks=[]
def ck(name, cond): checks.append((name,bool(cond)))
ck('package version',json.loads((root/'package.json').read_text())['version']=='2.0.5')
ck('tauri version',json.loads((root/'src-tauri'/'tauri.conf.json').read_text())['version']=='2.0.5')
ck('cargo version','version = "2.0.5"' in (root/'src-tauri'/'Cargo.toml').read_text())
ck('main.rs exists',(root/'src-tauri'/'src'/'main.rs').exists())
ck('Vehicle operations permission offered',"['pickVehicleStock','My Vehicle Stock Operations']" in dist)
ck('Mini Store operations permission offered',"['pickMiniStore','My Mini Store Stock Operations']" in dist)
ck('existing stock permission migration','migrateExistingStockOperationPermissions' in dist)
ck('Mini Store migration permission',"perms.push('pickMiniStore')" in dist)
ck('Vehicle migration permission',"perms.push('pickVehicleStock')" in dist)
ck('Sales Return destination field','id="r_destination"' in sales)
ck('cashier assignment destination filter','function srAssignedTo' in sales)
ck('admin warehouse destination',"kind:'warehouse',id:'main_warehouse'" in sales)
ck('vehicle destination inventory key',"nag_location_inventory_v1" in sales)
ck('Mini Store destination inventory key',"nag_mini_store_inventory_v1" in sales)
ck('destination stock adjustment','function srAdjustDestination' in sales)
ck('destination change transition','function srApplyStockTransition' in sales)
ck('return edit rollback','function srReverseStockTransition' in sales)
ck('return PDF destination','<b>Stock Destination:</b>' in sales)
ck('return history destination','<th>Stock Destination</th>' in sales)
ck('return Excel destination',"'Stock Destination':srDestinationLabel" in sales)
ck('cashier Vehicle Price UI hidden',".vehicle-col,.vehicle-field" in inv and "el.style.display=isAdminUser()?'':'none'" in inv)
ck('cashier PDF Vehicle Price conditional',"if(showVehicle)headers.push('<th>Vehicle Price</th>')" in inv)
ck('cashier Excel Vehicle Price conditional',"if(isAdminUser()){var vehicleMap=loadVehiclePriceMap();row['Vehicle Price']" in inv)
ck('Admin Vehicle Price retained','Vehicle Price' in inv)
ck('no new SQL readme','No new Supabase SQL is required' in (root/'CASHIER_RETURN_ROUTING_PRICE_PRIVACY_v205_README.txt').read_text())
for name,source in [('Sales Return',sales),('Inventory',inv),('Desktop shell',dist)]:
    scripts=re.findall(r'<script[^>]*>(.*?)</script>',source,re.S)
    temp=root/('.validate_'+name.lower().replace(' ','_')+'.js')
    temp.write_text('\n'.join(scripts),encoding='utf-8')
    try:
        r=subprocess.run(['node','--check',str(temp)],capture_output=True,text=True)
        ck(name+' JavaScript syntax',r.returncode==0)
        if r.returncode!=0: print(r.stderr)
    finally: temp.unlink(missing_ok=True)
for module,source in [('SALESRETURN',sales),('INVENTORY',inv)]:
    m=re.search(r'\b'+module+r'=b64utf8\("([A-Za-z0-9+/=]+)"\)',dist)
    ck(module+' embedded',m is not None)
    ck(module+' embedded matches',bool(m) and base64.b64decode(m.group(1)).decode('utf-8')==source)
failed=[n for n,o in checks if not o]
for n,o in checks: print(('PASS ' if o else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed: sys.exit(1)
