from pathlib import Path
import base64,json,re,subprocess,sys
root=Path(__file__).resolve().parent
employee=(root/'EMPLOYEES.html').read_text(encoding='utf-8')
decoded=(root/'EMPLOYEES_v200_DECODED.html').read_text(encoding='utf-8')
dist=(root/'dist'/'index.html').read_text(encoding='utf-8')
sql=(root/'SUPABASE_EMPLOYEE_SAVE_FIX_v200.sql').read_text(encoding='utf-8')
checks=[]
def check(name,condition): checks.append((name,bool(condition)))
check('package version',json.loads((root/'package.json').read_text())['version']=='2.0.0')
check('tauri version',json.loads((root/'src-tauri'/'tauri.conf.json').read_text())['version']=='2.0.0')
check('cargo version','version = "2.0.0"' in (root/'src-tauri'/'Cargo.toml').read_text())
check('main.rs present',(root/'src-tauri'/'src'/'main.rs').exists())
check('license number input','id="f_driving_license"' in employee)
check('license expiry input','id="f_driving_license_expiry"' in employee)
check('license search','driving_license_no' in employee and "$('search').value" in employee)
check('license table','License:' in employee)
check('license PDF columns','License No.' in employee and 'License Expiry' in employee)
check('save uses update by id',".update(row).eq('id',editingId)" in employee)
check('new save uses insert without id',"request=sb.from('nag_employees').insert(row)" in employee)
check('old upsert removed',"upsert(row,{onConflict:'emp_code'})" not in employee)
check('id is not added to payload','row.id=editingId' not in employee)
check('legacy employee number compatibility','employee_no:code' in employee)
check('legacy name compatibility','name:nameEn||nameAr||code' in employee)
check('legacy mobile compatibility','mobile:phone' in employee)
check('duplicate save protection','savingEmployee' in employee and "textContent='Saving...'" in employee)
check('clear generated id error','generated automatically' in employee or 'employee ID is automatic' in employee)
check('SQL adds license number','add column if not exists driving_license_no text' in sql)
check('SQL adds license expiry','add column if not exists driving_license_expiry date' in sql)
check('SQL does not insert id','insert into public.nag_employees' not in sql.lower())
check('SQL handles identity sequence','pg_get_serial_sequence' in sql)
check('SQL RLS policy','nag_employees_full_access_v200' in sql)
check('SQL schema reload',"notify pgrst, 'reload schema'" in sql)
check('decoded source matches',employee==decoded)
m=re.search(r'var EMPLOYEES=b64utf8\("([A-Za-z0-9+/=]+)"\);',dist)
check('embedded employee found',m is not None)
check('embedded employee matches',bool(m) and base64.b64decode(m.group(1)).decode('utf-8')==employee)
scripts=re.findall(r'<script>(.*?)</script>',employee,flags=re.S)
temp=root/'.validate_employee_v200.js'; temp.write_text('\n'.join(scripts),encoding='utf-8')
try:
 result=subprocess.run(['node','--check',str(temp)],capture_output=True,text=True)
 check('Employee JavaScript syntax',result.returncode==0)
finally: temp.unlink(missing_ok=True)
failed=[n for n,o in checks if not o]
for n,o in checks: print(('PASS ' if o else 'FAIL ')+n)
print(f'\nRESULT: {len(checks)-len(failed)} passed, {len(failed)} failed')
if failed: sys.exit(1)
